CREATE TABLE [dbo].[ExtractedKeyRatios] (
    [Id]                              UNIQUEIDENTIFIER NOT NULL,
    [DataSourceId]                    UNIQUEIDENTIFIER NOT NULL,
    [Year]                            INT              NOT NULL,
    [ReturnOnAssets]                  FLOAT (53)       NULL,
    [ReturnOnEquity]                  FLOAT (53)       NULL,
    [ReturnOnInvestedCapital]         FLOAT (53)       NULL,
    [ReturnOnCapitalEmployed]         FLOAT (53)       NULL,
    [ReturnOnTangibleCapitalEmployed] FLOAT (53)       NULL,
    [GrossMargin]                     FLOAT (53)       NULL,
    [EbitdaMargin]                    FLOAT (53)       NULL,
    [OperatingMargin]                 FLOAT (53)       NULL,
    [PretaxMargin]                    FLOAT (53)       NULL,
    [NetMargin]                       FLOAT (53)       NULL,
    [FreeCashMargin]                  FLOAT (53)       NULL,
    [AssetsToEquity]                  FLOAT (53)       NULL,
    [EquityToAssets]                  FLOAT (53)       NULL,
    [DebtToEquity]                    FLOAT (53)       NULL,
    [DebtToAssets]                    FLOAT (53)       NULL,
    [FreeCashFlow]                    MONEY            NULL,
    [BookValue]                       MONEY            NULL,
    [TangibleBookValue]               MONEY            NULL,
    [MarketCapitalization]            MONEY            NULL,
    [PriceToEarnings]                 FLOAT (53)       NULL,
    [PriceToBook]                     FLOAT (53)       NULL,
    [PriceToSales]                    FLOAT (53)       NULL,
    [DividendsPerShare]               FLOAT (53)       NULL,
    [PayoutRatio]                     FLOAT (53)       NULL,
    [CompanyId]                       UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]                     DATETIME2 (3)    NOT NULL,
    [DateUpdated]                     DATETIME2 (3)    NOT NULL,
    CONSTRAINT [PK_ExtractedKeyRatios] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExtractedKeyRatios_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([Id]),
    CONSTRAINT [FK_ExtractedKeyRatios_DataSources] FOREIGN KEY ([DataSourceId]) REFERENCES [dbo].[DataSources] ([Id])
);

