CREATE TABLE [dbo].[ExtractedCashFlowStatements] (
    [Id]                        UNIQUEIDENTIFIER NOT NULL,
    [DataSourceId]              UNIQUEIDENTIFIER NOT NULL,
    [Year]                      INT              NOT NULL,
    [DepreciationAmortization]  MONEY            NULL,
    [ChangeInWorkCapital]       MONEY            NULL,
    [ChangeInDeferredTax]       MONEY            NULL,
    [StockBasedCompensation]    MONEY            NULL,
    [OperationsOther]           MONEY            NULL,
    [CashFromOperations]        MONEY            NULL,
    [PropertyPlanEquipment]     MONEY            NULL,
    [Acquisitions]              MONEY            NULL,
    [Investments]               MONEY            NULL,
    [Intangibles]               MONEY            NULL,
    [InvestingOther]            MONEY            NULL,
    [CashFromInvesting]         MONEY            NULL,
    [IssuanceCommonStockNet]    MONEY            NULL,
    [IssuancePreferredStockNet] MONEY            NULL,
    [IssuanceDebtNet]           MONEY            NULL,
    [CashPaidForDividends]      MONEY            NULL,
    [FinancingOther]            MONEY            NULL,
    [CashFromFinancing]         MONEY            NULL,
    [CompanyId]                 UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]               DATETIME2 (3)    NOT NULL,
    [DateUpdated]               DATETIME2 (3)    NOT NULL,
    CONSTRAINT [PK_ExtractedCashFlowStatements] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExtractedCashFlowStatements_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([Id]),
    CONSTRAINT [FK_ExtractedCashFlowStatements_DataSources] FOREIGN KEY ([DataSourceId]) REFERENCES [dbo].[DataSources] ([Id])
);

