CREATE TABLE [dbo].[ExtractedBalanceSheets] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [DataSourceId]             UNIQUEIDENTIFIER NOT NULL,
    [Year]                     INT              NOT NULL,
    [CashEquivalents]          MONEY            NULL,
    [ShortTermInvestments]     MONEY            NULL,
    [AccountsReceivable]       MONEY            NULL,
    [OtherCurrentAssets]       MONEY            NULL,
    [TotalCurrentAssets]       MONEY            NULL,
    [Investments]              MONEY            NULL,
    [PropertyPlanEquipmentNet] MONEY            NULL,
    [Goodwill]                 MONEY            NULL,
    [OtherIntangibleAssets]    MONEY            NULL,
    [OtherAssets]              MONEY            NULL,
    [TotalAssets]              MONEY            NULL,
    [AccountsPayable]          MONEY            NULL,
    [TaxPayable]               MONEY            NULL,
    [AccruedLiabilities]       MONEY            NULL,
    [ShortTermDebt]            MONEY            NULL,
    [DeferedRevenue1]          MONEY            NULL,
    [OtherCurrentLiabilities]  MONEY            NULL,
    [TotalCurrentLiabilities]  MONEY            NULL,
    [LongTermDebt]             MONEY            NULL,
    [CapitalLeases]            MONEY            NULL,
    [DeferredRevenue2]         MONEY            NULL,
    [OtherLiabilities]         MONEY            NULL,
    [TotalLiabilities]         MONEY            NULL,
    [RetainedEarnings]         MONEY            NULL,
    [PaidInCapital]            MONEY            NULL,
    [CommonStock]              MONEY            NULL,
    [AOCI]                     MONEY            NULL,
    [TreasuryStock]            MONEY            NULL,
    [Other]                    MONEY            NULL,
    [ShareholdersEquity]       MONEY            NULL,
    [LiabilitiesAndEquity]     MONEY            NULL,
    [CompanyId]                UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]              DATETIME2 (3)    NOT NULL,
    [DateUpdated]              DATETIME2 (3)    NOT NULL,
    CONSTRAINT [PK_ExtractedBalanceSheets] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExtractedBalanceSheets_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([Id]),
    CONSTRAINT [FK_ExtractedBalanceSheets_DataSources] FOREIGN KEY ([DataSourceId]) REFERENCES [dbo].[DataSources] ([Id])
);

